### ISSUE TITLE
EXCEPTION: 11DbException

### ISSUE THREAD

**Issue by daciolimasantos** [bumbacoin/stronghands-012x#11]
Hello, I now have a lot of problems.

1° - There's two transanctions that never go to the wallets.
txid1: f5ed09d9936619709874aa7b305f0d4bed3bf24cea263b09f002a0ae184dfef0
from: SP6vrVUpKhRxebqH3zjgFwHpU3gqs4HM16
to: SUXCuR5Zm2yvXX8fwF1GhzFwmJmQcMMnbY

txid:ddb86d3b92ca0ab69144cec028ab70164659c252269ae1bdd8d06638e0835368
from: SP6vrVUpKhRxebqH3zjgFwHpU3gqs4HM16
to: Sbued2P4tWrG3seZNxtE1VT1rQoJkcWWtV

2° - try to run v153 but only the v152 runs okay, all previous versions show up the same problem below:
EXCEPTION: 11DbException
Db::open:Invalid argument

Please, somebody can help me?

**Comment by zahidaliayub** [comment]
v153
EXCEPTION: 11DbException
Db::open:Invalid argument

**Comment by bumbacoin** [comment]
this is not the place to assist with these problems,
this is a problem with your local copy of the blockchain.

please come to discord and ask for assistance thank you.
