### ISSUE TITLE
Does staonghands 1.5.3 release has a virus?

### ISSUE THREAD

**Issue by jeong760** [bumbacoin/stronghands-012x#12]
Dears,

When I download a stronghands 1.5.3 my computer displayed this message. so cannot download.
Could you check it?

![capture](https://user-images.githubusercontent.com/18043565/37572086-44188c54-2b49-11e8-9216-2205a424661e.JPG)

**Comment by nsung129** [comment]
Me too. i can't download it

**Comment by K2E2014** [comment]
Either can I. I have had it working for a couple of weeks then I got/get the same messages as above. And now I can't re-download it.

Please help!

**Comment by bumbacoin** [comment]
many anti-virus checkers will find viruses in many coin wallets,

you will need to whitelist the exe.
please come into discord for assistance.
