### ISSUE TITLE
Block Count Comparison mistake?

### ISSUE THREAD

**Issue by Kino12345** [bumbacoin/stronghands-012x#3]
https://github.com/bumbacoin/stronghands/blob/a75b392c30a9dc52ec73fdd5942d107a986b6860/src/main.cpp#L996

if (nBestHeight > 593500)
↓
if (nBestHeight > 589500)

**Comment by bumbacoin** [comment]
this is deliberate

pow will change values,
then later pos will change values,

then later they will change values together.
